[project]
name = "alx-backend-python"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "djangorestframework>=3.16.0",
    "drf-nested-routers>=0.94.2",
]
